name: todak_shop
description: "A Flutter project for digital online Todak Shop"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  hive: ^2.2.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.10
  jwt_decoder: ^2.0.1
  lottie: ^3.0.0
  mockito: ^5.4.4
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  talker_dio_logger: ^4.0.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter_gen:
  output: lib/core/gen

flutter:
  assets:
    - assets/
    - assets/lottie/
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  